In [1]:
import numpy as np

from Angle import Angle
from Distance import Distance
from Net import Network
d = Distance()
a = Angle()
n = Network([d,a])

n.P

LSA iteration: 1
x_0: 
[[5656.89]
 [2475.56]
 [ 663.9 ]
 [2943.91]]
l_0: 
[[2.46393029e+03]
 [3.41462542e+03]
 [5.21612074e+03]
 [6.04296152e+03]
 [5.08495139e+03]
 [5.01490786e+03]
 [1.46829987e+00]
 [6.59318691e-01]
 [1.01397409e+00]
 [5.76847928e-01]
 [2.19966394e+00]
 [3.65080781e-01]
 [1.29687519e+00]
 [1.35202081e+00]
 [4.92696649e-01]
 [9.66072741e-01]
 [1.26320067e+00]
 [9.12319238e-01]]
S_hat:
[[ 0.13154149]
 [-0.03560444]
 [-0.0071064 ]
 [ 0.11681186]]
x_hat: 
[[5657.02154149]
 [2475.52439556]
 [ 663.8928936 ]
 [2944.02681186]]
A: 
[[ 3.07251388e-01  9.51628386e-01  0.00000000e+00  0.00000000e+00]
 [-9.15197018e-01  4.03006723e-01  0.00000000e+00  0.00000000e+00]
 [ 2.12436609e-01 -9.77174850e-01  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -6.42879321e-01 -7.65967479e-01]
 [ 0.00000000e+00  0.00000000e+00 -8.33035298e-01  5.53219841e-01]
 [ 9.95629459e-01 -9.33915463e-02 -9.95629459e-01  9.33915463e-02]
 [ 2.68200047e-04 -3.92722377e-04  0.00000000e+00 

matrix([[0.5625, 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
         0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
         0.    , 0.    ],
        [0.    , 0.5625, 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
         0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
         0.    , 0.    ],
        [0.    , 0.    , 0.5625, 0.    , 0.    , 0.    , 0.    , 0.    ,
         0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
         0.    , 0.    ],
        [0.    , 0.    , 0.    , 0.5625, 0.    , 0.    , 0.    , 0.    ,
         0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
         0.    , 0.    ],
        [0.    , 0.    , 0.    , 0.    , 0.5625, 0.    , 0.    , 0.    ,
         0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
         0.    , 0.    ],
        [0.    , 0.    , 0.    , 0.    , 0.    , 0.5625, 0.    , 0.    ,
         0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.

In [2]:
n.models[0].x_0

matrix([[5656.89],
        [2475.56],
        [ 663.9 ],
        [2943.91]])

In [3]:
n.models[1].x_0

matrix([[5656.89],
        [2475.56],
        [ 663.9 ],
        [2943.91]])

In [4]:
n.x_0

matrix([[5657.41616595],
        [2475.41758226],
        [ 663.87157441],
        [2944.37724746]])